# Generated by Django 5.2.3 on 2025-06-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_collection_featured_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
