# Generated by Django 5.2.3 on 2025-06-29 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_customer_options_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-placed_at'], 'permissions': [('cancel_order', 'Can cancel order')], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
